server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:products
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    schemas: migrations
    group: true
    out-of-order: true
